version: "2"

linters-settings:
  custom:
    gologlinter:
      path: ./gologlinter
      description: "Checks log messages"
      original-url: github.com/aster-ix/golog-linter

linters:
  enable-all: true
  disable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused